# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mongodb:
    image: docker.io/cruizba/ubuntu-bitnami-mongodb:latest
    environment:
      - BITNAMI_DEBUG=true
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local
