name: Build and push Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

env:
  MONGODB_MAJOR: '8'
  MONGODB_MAJOR_MINOR: '8.0'
  MONGODB_VERSION: '8.0.12'
  BUILD_NUMBER: 1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: cruizba
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push standalone image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            cruizba/ubuntu-bitnami-mongodb:${{ env.MONGODB_MAJOR }}
            cruizba/ubuntu-bitnami-mongodb:${{ env.MONGODB_MAJOR_MINOR }}
            cruizba/ubuntu-bitnami-mongodb:${{ env.MONGODB_VERSION }}
            cruizba/ubuntu-bitnami-mongodb:${{ env.MONGODB_VERSION }}-r${{ env.BUILD_NUMBER }}
            cruizba/ubuntu-bitnami-mongodb:latest

      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v0.2.4

      - name: Scan Docker image for vulnerabilities
        run: trivy image cruizba/ubuntu-bitnami-mongodb:latest --exit-code 0 --no-progress --ignore-unfixed --format json --output trivy.json

      - name: Format Trivy results
        shell: pwsh
        run: Get-Content trivy.json | ConvertFrom-Json | Select-Object -ExpandProperty Results | Select-Object -ExpandProperty Vulnerabilities | Select-Object Severity, PkgName, InstalledVersion, FixedVersion, Status, Title | ConvertTo-Html -Fragment | Out-File trivy.html

      - name: Add Trivy results to GitHub summary
        run: cat trivy.html >> $GITHUB_STEP_SUMMARY
